### ISSUE TITLE
Provides no binaries

### ISSUE THREAD

**Issue by Mailaender** [flathub/org.freedesktop.Sdk.Extension.haskell#83]
```yaml
[..]
runtime-version: '21.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.haskell
[..]

  - name: haskell
    buildsystem: simple
    build-commands:
      - /usr/lib/sdk/haskell/enable.sh

[..]
```
fails with
> /bin/sh: line 1: stack: command not found
> /bin/sh: line 1: runhaskell: command not found
